compile image added

diff --git a/spark-examples/docker/copy/bin/start-spark-master b/spark-examples/docker/copy/bin/start-spark-master
--- a/spark-examples/docker/copy/bin/start-spark-master
+++ b/spark-examples/docker/copy/bin/start-spark-master
@@ -1,30 +1,33 @@
 #!/bin/bash
-function check {
+set -x
+function check_start {
     if [ $1 -ne 0 ]; then
-        echo "Failed to run $2: $1"
+        echo "Failed to start $2: $1"
         exit $1
     fi
 }
+
+function check_running {
+    ps aux | grep $1 | grep -q -v grep
+    status=$?
+    if [ $status -ne 0 ]; then
+        echo "$1 stopped. Terminating"
+        exit $status
+    fi
+}
+
 hostname=`hostname`
 syslogd -R fluentd:5140
-check $? fluentd
+check_start $? syslogd
 
 start-hadoop-namenode | logger -t $hostname.namenode &
-check $? start-hadoop-namenode
+check_start $? start-hadoop-namenode
 
 spark-class org.apache.spark.deploy.master.Master | logger -t $hostname.sparkmaster &
-check $? spark-master
+check_start $? spark-master
 
 while /bin/true; do
-    # ps aux |grep my_first_process |grep -q -v grep
-    # PROCESS_1_STATUS=$?
-    # ps aux |grep my_second_process |grep -q -v grep
-    # PROCESS_2_STATUS=$?
-    # # If the greps above find anything, they will exit with 0 status
-    # # If they are not both 0, then something is wrong
-    # if [ $PROCESS_1_STATUS -ne 0 -o $PROCESS_2_STATUS -ne 0 ]; then
-    #     echo "One of the processes has already exited."
-    #     exit -1
-    # fi
+    check_running start-hadoop-namenode
+    check_running org.apache.spark.deploy.master.Master
     sleep 60
 done
